[package]
name = "rust_workflow"
description = "github_action"
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

[[bin]]
edition = "2018"
name = "rust_workflow"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
