name: Unit tests, linting, and formatting

permissions: {}
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: |
          rustup override set stable
          rustup update stable
      - name: Run cargo build
        id: run_tests
        run: |
         ls
      - name: Lint
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check
